config/routes.rb
Rails.application.routes.draw do
  resources :topics

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <link href='//fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//s3.amazonaws.com/codecademy-content/courses/ltp/css/bootstrap.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class='container'>
	<%= yield %>
</div>
</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
<div class="well col-md-6 col-md-offset-3">
<h1><center><% if params['action'] == 'edit' %>Edit<% elsif params['action'] == 'new' %>New<% end %> Topic</center></h1>
 <div class="form-group">
      <%= f.label :title, class: "control-label" %><br>
      <%= f.text_field :title, class: "form-control" %>
 </div>
 <div class="form-group">
      <%= f.label :description, class: "control-label" %><br>
      <%= f.text_area :description, class: "form-control" %>
 </div>
 
  
  <div class="form-group">
  <center><%= f.submit %></center>
  </div>
<% end %>

<center><%= link_to 'Back', topics_path %></center>
<center><%= link_to 'Show', @topic %> </center>
</div>

app/views/topics/edit.html.erb
<%= render 'form' %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <ul>
   <h1><center>Main Page</center></h1>
</ul>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <div class="row">
       <div class="col-md-6">    
         <th>Title</th>
       </div>
       <div class="col-md-6"> 
        <th>Description</th>
       </div>
      </div>  
        </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.description %></td>
        <td><%= link_to 'Show', topic, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path, class: "btn btn-default" %>

app/views/topics/new.html.erb
<%= render 'form' %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well col-md-6 col-md-offset-3">
  <div class="form-group">
    <p>
      <strong>Title:</strong>
      </p>
      <p>
      <%= @topic.title %>
      </p>
  </div>

  <div class="form-group">
    <p>
      <strong>Description:</strong>
     </p>
     <p>
      <%= @topic.description %>
      </p>
  </div>




<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>


</div> 